### ISSUE TITLE
Support for `--template-files` option

### ISSUE THREAD

**Issue by ludovicm67** [losisin/helm-docs-github-action#204]
Would it be possible to have a way to set the `--template-files` helm-docs option using a dedicated GitHub Action input?

See: https://github.com/norwoodj/helm-docs?tab=readme-ov-file#markdown-rendering

**Comment by losisin** [comment]
@ludovicm67 done!

**Comment by ludovicm67** [comment]
@losisin Great, thanks a lot! 👍
